DATA_FILE_HEADER_RECORD:
  FIELDS:
    - NAME: REC_TYPE
      RANGE: [0, 0]
    - NAME: AMEX_APPL_AREA
      RANGE: [1, 100]
    - NAME: SAID
      RANGE: [101, 106]
    - NAME: DATATYPE
      RANGE: [107, 111]
    - NAME: CCYYDDD
      RANGE: [112, 118]
      TYPE: julian
    - NAME: 0HHMMSS
      RANGE: [119, 125]
      TYPE: numeric
CHARGEBACK_DETAIL_RECORD:
  RECURRING: true
  FIELDS:
    - NAME: REC_TYPE
      RANGE: [0, 0]
    - NAME: SE_NUMB
      RANGE: [6, 15]
    - NAME: CM_ACCT_NUMB
      RANGE: [26, 44]
    - NAME: CURRENT_CASE_NUMBER
      RANGE: [46, 56]
    - NAME: CURRENT_ACTION_NUMBER
      RANGE: [57, 58]
    - NAME: PREVIOUS_CASE_NUMBER
      RANGE: [59, 69]
    - NAME: PREVIOUS_ACTION_NUMBER
      RANGE: [70, 71]
    - NAME: RESOLUTION
      RANGE: [72, 72]
    - NAME: FROM_SYSTEM
      RANGE: [73, 73]
    - NAME: REJECTS_TO_SYSTEM
      RANGE: [74, 74]
    - NAME: DISPUTES_TO_SYSTEM
      RANGE: [75, 75]
    - NAME: DATE_OF_ADJUSTMENT
      RANGE: [76, 83]
      TYPE: date(%Y%m%d)
    - NAME: DATE_OF_CHARGE
      RANGE: [84, 91]
      TYPE: date(%Y%m%d)
    - NAME: AMEX_ID
      RANGE: [92, 98]
    - NAME: CASE_TYPE
      RANGE: [104, 109]
    - NAME: LOC_NUMB
      RANGE: [110, 124]
    - NAME: CB_REAS_CODE
      RANGE: [125, 127]
    - NAME: CB_AMOUNT
      RANGE: [128, 144]
      TYPE: numeric
    - NAME: CB_ADJUSTMENT_NUMBER
      RANGE: [145, 150]
    - NAME: CB_RESOLUTION_ADJ_NUMBER
      RANGE: [151, 156]
    - NAME: CB_REFERENCE_CODE
      RANGE: [157, 168]
    - NAME: BILLED_AMOUNT
      RANGE: [182, 198]
      TYPE: numeric
    - NAME: SOC_AMOUNT
      RANGE: [199, 215]
      TYPE: numeric
    - NAME: SOC_INVOICE_NUMBER
      RANGE: [216, 221]
    - NAME: ROC_INVOICE_NUMBER
      RANGE: [222, 227]
    - NAME: FOREIGN_AMT
      RANGE: [228, 242]
    - NAME: CURRENCY
      RANGE: [243, 245]
    - NAME: SUPP_TO_FOLLOW
      RANGE: [246, 246]
    - NAME: CM_NAME1
      RANGE: [247, 276]
    - NAME: CM_NAME2
      RANGE: [277, 306]
    - NAME: CM_ADDR1
      RANGE: [307, 336]
    - NAME: CM_ADDR2
      RANGE: [337, 366]
    - NAME: CM_CITY_STATE
      RANGE: [367, 396]
    - NAME: CM_ZIP
      RANGE: [397, 405]
    - NAME: CM_FIRST_NAME_1
      RANGE: [406, 417]
    - NAME: CM_MIDDLE_NAME_1
      RANGE: [418, 429]
    - NAME: CM_LAST_NAME_1
      RANGE: [430, 449]
    - NAME: CM_ORIG_ACCT_NUM
      RANGE: [450, 464]
    - NAME: CM_ORIG_NAME
      RANGE: [465, 494]
    - NAME: CM_ORIG_FIRST_NAME
      RANGE: [495, 506]
    - NAME: CM_ORIG_MIDDLE_NAME
      RANGE: [507, 518]
    - NAME: CM_ORIG_LAST_NAME
      RANGE: [519, 538]
    - NAME: NOTE1
      RANGE: [539, 604]
    - NAME: NOTE2
      RANGE: [605, 682]
    - NAME: NOTE3
      RANGE: [683, 742]
    - NAME: NOTE4
      RANGE: [743, 802]
    - NAME: NOTE5
      RANGE: [803, 862]
    - NAME: NOTE6
      RANGE: [863, 922]
    - NAME: NOTE7
      RANGE: [923, 982]
    - NAME: TRIUMPH_SEQ_NO
      RANGE: [983, 984]
    - NAME: AIRLINE_TKT_NUM
      RANGE: [1030, 1043]
    - NAME: AL_SEQUENCE_NUMBER
      RANGE: [1044, 1045]
    - NAME: FOLIO_REF
      RANGE: [1046, 1063]
    - NAME: MERCH_ORDER_NUM
      RANGE: [1064, 1073]
    - NAME: MERCH_ORDER_DATE
      RANGE: [1074, 1081]
      TYPE: date(%Y%m%d)
    - NAME: CANC_NUM
      RANGE: [1082, 1101]
    - NAME: CANC_DATE
      RANGE: [1102, 1109]
      TYPE: date(%Y%m%d)
    - NAME: FINCAP_TRACKING_ID
      RANGE: [1110, 1120]
    - NAME: FINCAP_FILE_SEQ_NUM
      RANGE: [1121, 1126]
    - NAME: FINCAP_BATCH_NUMBER
      RANGE: [1127, 1130]
    - NAME: FINCAP_BATCH_INVOICE_DT
      RANGE: [1131, 1138]
      TYPE: date(%Y%m%d)
    - NAME: LABEL1
      RANGE: [1139, 1163]
    - NAME: DATA1
      RANGE: [1164, 1188]
    - NAME: LABEL2
      RANGE: [1189, 1213]
    - NAME: DATA2
      RANGE: [1214, 1238]
    - NAME: LABEL3
      RANGE: [1239, 1263]
    - NAME: DATA3
      RANGE: [1264, 1288]
    - NAME: LABEL4
      RANGE: [1289, 1313]
    - NAME: DATA4
      RANGE: [1314, 1338]
    - NAME: LABEL5
      RANGE: [1339, 1363]
    - NAME: DATA5
      RANGE: [1364, 1388]
    - NAME: LABEL6
      RANGE: [1389, 1413]
    - NAME: DATA6
      RANGE: [1414, 1438]
    - NAME: LABEL7
      RANGE: [1439, 1463]
    - NAME: DATA7
      RANGE: [1464, 1488]
    - NAME: LABEL8
      RANGE: [1489, 1513]
    - NAME: DATA8
      RANGE: [1514, 1538]
    - NAME: LABEL9
      RANGE: [1539, 1563]
    - NAME: DATA9
      RANGE: [1564, 1588]
    - NAME: LABEL10
      RANGE: [1589, 1613]
    - NAME: DATA10
      RANGE: [1614, 1638]
    - NAME: LABEL11
      RANGE: [1639, 1663]
    - NAME: DATA11
      RANGE: [1664, 1688]
    - NAME: CM_ACCNT_NUMB_EXD
      RANGE: [1689, 1707]
    - NAME: CASE_NUMBER_EXD
      RANGE: [1714, 1729]
    - NAME: IND_FORM_CODE
      RANGE: [1765, 1766]
    - NAME: IND_REF_NUMBER
      RANGE: [1767, 1796]
    - NAME: LOC_REF_NUMBER
      RANGE: [1800, 1814]
    - NAME: PASSENGER_NAME
      RANGE: [1815, 1834]
    - NAME: PASSENGER_FIRST_NAME
      RANGE: [1835, 1846]
    - NAME: PASSENGER_MIDDLE_NAME
      RANGE: [1847, 1858]
    - NAME: PASSENGER_LAST_NAME
      RANGE: [1859, 1878]
    - NAME: SE_PROCESS_DATE
      RANGE: [1879, 1881]
      TYPE: julian
    - NAME: RETURN_DATE
      RANGE: [1882, 1887]
      TYPE: date(%y%m%d)
    - NAME: CREDIT_RECEIPT_NUMBER
      RANGE: [1888, 1902]
    - NAME: RETURN_TO_NAME
      RANGE: [1903, 1926]
    - NAME: RETURN_TO_STREET
      RANGE: [1927, 1943]
    - NAME: CARD_DEPOSIT
      RANGE: [1944, 1944]
    - NAME: ASSURED_RESERVATION
      RANGE: [1945, 1945]
    - NAME: RES_CANCELLED
      RANGE: [1946, 1946]
    - NAME: RES_CANCELLED_DATE
      RANGE: [1947, 1952]
      TYPE: date(%y%m%d)
    - NAME: CANCEL_ZONE
      RANGE: [1953, 1953]
    - NAME: RESERVATION_MADE_FOR
      RANGE: [1954, 1959]
    - NAME: RESERVATION_LOCATION
      RANGE: [1960, 1979]
    - NAME: RESERVATION_MADE_ON
      RANGE: [1980, 1985]
      TYPE: date(%y%m%d)
    - NAME: RENTAL_AGREEMENT_NUMBER
      RANGE: [1986, 2003]
    - NAME: MERCHANDISE_TYPE
      RANGE: [2004, 2023]
    - NAME: MERCHANDISE_RETURNED
      RANGE: [2024, 2024]
    - NAME: RETURNED_NAME
      RANGE: [2025, 2048]
    - NAME: RETURNED_DATE
      RANGE: [2049, 2054]
      TYPE: date(%y%m%d)
    - NAME: RETURNED_HOW
      RANGE: [2055, 2062]
    - NAME: RETURNED_REASON
      RANGE: [2063, 2112]
    - NAME: STORE_CREDIT_RECEIVED
      RANGE: [2113, 2113]
DATA_FILE_TRAILER_RECORD:
  TRAILER: true
  FIELDS:
    - NAME: REC_TYPE
      RANGE: [0, 0]
    - NAME: AMEX_APPL_AREA
      RANGE: [1, 100]
    - NAME: SAID
      RANGE: [101, 106]
    - NAME: DATATYPE
      RANGE: [107, 111]
    - NAME: CCYYDDD
      RANGE: [112, 118]
      TYPE: julian
    - NAME: 0HHMMSS
      RANGE: [119, 125]
      TYPE: numeric
    - NAME: STARS_FILESEQ_NB
      RANGE: [126, 128]
      TYPE: numeric
