DATA_FILE_HEADER_RECORD:
  FIELDS:
    - NAME: DF_HDR_RECORD_TYPE
      RANGE: [0, 4]
    - NAME: DF_HDR_DATE
      RANGE: [5, 12]
      TYPE: date
    - NAME: DF_HDR_TIME
      RANGE: [13, 16]
    - NAME: DF_HDR_FILE_ID
      RANGE: [17, 22]
      TYPE: numeric
    - NAME: DF_HDR_FILE_NAME
      RANGE: [23, 42]
DETAIL_RECORD:
  ABSTRACT: true
  RECURRING: true
  TYPE_FIELD: [43, 44]
  TYPE_MAPPING:
    '00': SUMMARY_RECORD
    '10': SUMMARY_OF_CHARGE_DETAIL_RECORD
    '11': RECORD_OF_CHARGE_DETAIL_RECORD
    '20': CHARGEBACK_DETAIL_RECORD
    '30': ADJUSTMENT_DETAIL_RECORD
    '50': OTHER_FEES_AND_REVENUES_DETAIL_RECORDS
  TYPES:
    SUMMARY_RECORD:
      RECURRING: true
      FIELDS:
        - NAME: AMEX_PAYEE_NUMBER
          RANGE: [0, 9]
          TYPE: numeric
        - NAME: AMEX_SORT_FIELD_1
          RANGE: [10, 19]
        - NAME: AMEX_SORT_FIELD_2
          RANGE: [20, 29]
        - NAME: PAYMENT_YEAR
          RANGE: [30, 33]
          TYPE: numeric
        - NAME: PAYMENT_NUMBER
          RANGE: [34, 41]
        - NAME: RECORD_TYPE
          RANGE: [42, 42]
        - NAME: DETAIL_RECORD_TYPE
          RANGE: [43, 44]
        - NAME: PAYMENT_DATE
          RANGE: [45, 51]
          TYPE: julian
        - NAME: PAYMENT_AMOUNT
          RANGE: [52, 62]
          TYPE: decimal
        - NAME: DEBIT_BALANCE_AMOUNT
          RANGE: [63, 71]
          TYPE: decimal
        - NAME: ABA_BANK_NUMBER
          RANGE: [72, 80]
          TYPE: numeric
        - NAME: SE_DDA_NUMBER
          RANGE: [81, 97]
    SUMMARY_OF_CHARGE_DETAIL_RECORD:
      RECURRING: true
      FIELDS:
        - NAME: AMEX_PAYEE_NUMBER
          RANGE: [0, 9]
          TYPE: numeric
        - NAME: AMEX_SE_NUMBER
          RANGE: [10, 19]
          TYPE: numeric
        - NAME: SE_UNIT_NUMBER
          RANGE: [20, 29]
        - NAME: PAYMENT_YEAR
          RANGE: [30, 33]
          TYPE: numeric
        - NAME: PAYMENT_NUMBER
          RANGE: [34, 41]
        - NAME: RECORD_TYPE
          RANGE: [42, 42]
        - NAME: DETAIL_RECORD_TYPE
          RANGE: [43, 44]
        - NAME: SE_BUSINESS_DATE
          RANGE: [45, 51]
          TYPE: julian
        - NAME: AMEX_PROCESS_DATE
          RANGE: [52, 58]
          TYPE: julian
        - NAME: SOC_INVOICE_NUMBER
          RANGE: [59, 64]
          TYPE: numeric
        - NAME: SOC_AMOUNT
          RANGE: [65, 75]
          TYPE: decimal
        - NAME: DISCOUNT_AMOUNT
          RANGE: [76, 84]
          TYPE: decimal
        - NAME: SERVICE_FEE_AMOUNT
          RANGE: [85, 91]
          TYPE: decimal
        - NAME: NET_SOC_AMOUNT
          RANGE: [99, 109]
          TYPE: decimal
        - NAME: DISCOUNT_RATE
          RANGE: [110, 114]
          TYPE: numeric
        - NAME: SERVICE_FEE_RATE
          RANGE: [115, 119]
          TYPE: numeric
        - NAME: AMEX_GROSS_AMOUNT
          RANGE: [141, 151]
          TYPE: decimal
        - NAME: AMEX_ROC_COUNT
          RANGE: [152, 156]
        - NAME: TRACKING_ID
          RANGE: [157, 165]
          TYPE: numeric
        - NAME: CPC_INDICATOR
          RANGE: [166, 166]
        - NAME: AMEX_RO_COUNT_POA
          RANGE: [182, 188]
          TYPE: decimal
    RECORD_OF_CHARGE_DETAIL_RECORD:
      RECURRING: true
      FIELDS:
        - NAME: TLRR_AMEX_PAYEE_NUMBER
          RANGE: [0, 9]
          TYPE: numeric
        - NAME: TLRR_AMEX_SE_NUMBER
          RANGE: [10, 19]
          TYPE: numeric
        - NAME: TLRR_SE_UNIT_NUMBER
          RANGE: [20, 29]
        - NAME: TLRR_PAYMENT_YEAR
          RANGE: [30, 33]
          TYPE: numeric
        - NAME: TLRR_PAYMENT_NUMBER
          RANGE: [34, 41]
        - NAME: TLRR_RECORD_TYPE
          RANGE: [42, 42]
        - NAME: TLRR_DETAIL_RECORD_TYPE
          RANGE: [43, 44]
        - NAME: TLRR_SE_BUSINESS_DATE
          RANGE: [45, 51]
          TYPE: julian
        - NAME: TLRR_AMEX_PROCESS_DATE
          RANGE: [52, 58]
          TYPE: julian
        - NAME: TLRR_SOC_INVOICE_NUMBER
          RANGE: [59, 64]
          TYPE: numeric
        - NAME: TLRR_SOC_AMOUNT
          RANGE: [65, 77]
          TYPE: decimal
        - NAME: TLRR_ROC_AMOUNT
          RANGE: [78, 90]
          TYPE: decimal
        - NAME: TLRR_CM_NUMBER
          RANGE: [91, 105]
          TYPE: numeric
        - NAME: TLRR_CM_REF_NO
          RANGE: [106, 116]
        - NAME: TLRR_SE_REF
          RANGE: [117, 125]
        - NAME: TLRR_SE_REF_EXPANSION_FILLER
          RANGE: [126, 135]
        - NAME: TLRR_ROC_NUMBER
          RANGE: [136, 145]
        - NAME: TLRR_TRAN_DATE
          RANGE: [146, 152]
          TYPE: julian
        - NAME: TLRR_SE_REF_POA
          RANGE: [153, 182]
        - NAME: NON_COMPLIANT_INDICATOR
          RANGE: [183, 183]
        - NAME: NON_COMPLIANT_ERROR_CODE_1
          RANGE: [184, 187]
        - NAME: NON_COMPLIANT_ERROR_CODE_2
          RANGE: [188, 191]
        - NAME: NON_COMPLIANT_ERROR_CODE_3
          RANGE: [192, 195]
        - NAME: NON_COMPLIANT_ERROR_CODE_4
          RANGE: [196, 199]
        - NAME: NON_SWIPED_INDICATOR
          RANGE: [200, 200]
    CHARGEBACK_DETAIL_RECORD:
      RECURRING: true
      FIELDS:
        - NAME: AMEX_PAYEE_NUMBER
          RANGE: [0, 9]
          TYPE: numeric
        - NAME: AMEX_SE_NUMBER
          RANGE: [10, 19]
          TYPE: numeric
        - NAME: SE_UNIT_NUMBER
          RANGE: [20, 29]
        - NAME: PAYMENT_YEAR
          RANGE: [30, 33]
          TYPE: numeric
        - NAME: PAYMENT_NUMBER
          RANGE: [34, 41]
        - NAME: RECORD_TYPE
          RANGE: [42, 42]
        - NAME: DETAIL_RECORD_TYPE
          RANGE: [43, 44]
        - NAME: SE_BUSINESS_DATE
          RANGE: [45, 51]
          TYPE: julian
        - NAME: AMEX_PROCESS_DATE
          RANGE: [52, 58]
          TYPE: julian
        - NAME: SOC_INVOICE_NUMBER
          RANGE: [59, 64]
          TYPE: numeric
        - NAME: SOC_AMOUNT
          RANGE: [65, 75]
          TYPE: decimal
        - NAME: CHARGEBACK_AMOUNT
          RANGE: [76, 84]
          TYPE: decimal
        - NAME: DISCOUNT_AMOUNT
          RANGE: [85, 93]
          TYPE: decimal
        - NAME: SERVICE_FEE_AMOUNT
          RANGE: [94, 100]
          TYPE: decimal
        - NAME: NET_CHARGEBACK_AMOUNT
          RANGE: [108, 116]
          TYPE: decimal
        - NAME: DISCOUNT_RATE
          RANGE: [117, 121]
          TYPE: numeric
        - NAME: SERVICE_FEE_RATE
          RANGE: [122, 126]
          TYPE: numeric
        - NAME: CHARGEBACK_REASON
          RANGE: [143, 422]
    ADJUSTMENT_DETAIL_RECORD:
      RECURRING: true
      FIELDS:
        - NAME: AMEX_PAYEE_NUMBER
          RANGE: [0, 9]
          TYPE: numeric
        - NAME: AMEX_SE_NUMBER
          RANGE: [10, 19]
          TYPE: numeric
        - NAME: SE_UNIT_NUMBER
          RANGE: [20, 29]
        - NAME: PAYMENT_YEAR
          RANGE: [30, 33]
          TYPE: numeric
        - NAME: PAYMENT_NUMBER
          RANGE: [34, 41]
        - NAME: RECORD_TYPE
          RANGE: [42, 42]
        - NAME: DETAIL_RECORD_TYPE
          RANGE: [43, 44]
        - NAME: AMEX_PROCESS_DATE
          RANGE: [45, 51]
          TYPE: julian
        - NAME: ADJUSTMENT_NUMBER
          RANGE: [52, 57]
          TYPE: numeric
        - NAME: ADJUSTMENT_AMOUNT
          RANGE: [58, 66]
          TYPE: decimal
        - NAME: DISCOUNT_AMOUNT
          RANGE: [67, 75]
          TYPE: decimal
        - NAME: SERVICE_FEE_AMOUNT
          RANGE: [76, 82]
          TYPE: decimal
        - NAME: NET_ADJUSTMENT_AMOUNT
          RANGE: [90, 98]
          TYPE: decimal
        - NAME: DISCOUNT_RATE
          RANGE: [99, 103]
          TYPE: numeric
        - NAME: SERVICE_FEE_RATE
          RANGE: [104, 108]
          TYPE: numeric
        - NAME: CARDMEMBER_NUMBER
          RANGE: [125, 141]
          TYPE: numeric
        - NAME: ADJUSTMENT_REASON
          RANGE: [142, 421]
    OTHER_FEES_AND_REVENUES_DETAIL_RECORDS:
      RECURRING: true
      FIELDS:
        - NAME: AMEX_PAYEE_NUMBER
          RANGE: [0, 9]
          TYPE: numeric
        - NAME: AMEX_SE_NUMBER
          RANGE: [10, 19]
          TYPE: numeric
        - NAME: SE_UNIT_NUMBER
          RANGE: [20, 29]
        - NAME: PAYMENT_YEAR
          RANGE: [30, 33]
          TYPE: numeric
        - NAME: PAYMENT_NUMBER
          RANGE: [34, 41]
        - NAME: RECORD_TYPE
          RANGE: [42, 42]
        - NAME: DETAIL_RECORD_TYPE
          RANGE: [43, 44]
        - NAME: AMEX_PROCESS_DATE
          RANGE: [45, 51]
          TYPE: julian
        - NAME: ASSET_BILLING_AMOUNT
          RANGE: [52, 60]
          TYPE: decimal
        - NAME: ASSET_BILLING_DESCRIPTION
          RANGE: [61, 126]
        - NAME: TAKE_ONE_COMMISSION_AMOUNT
          RANGE: [126, 134]
          TYPE: decimal
        - NAME: TAKE_ONE_DESCRIPTION
          RANGE: [135, 214]
        - NAME: OTHER_FEE_AMOUNT
          RANGE: [215, 223]
          TYPE: decimal
        - NAME: OTHER_FEE_DESCRIPTION
          RANGE: [224, 303]
        - NAME: ASSET_BILLING_TAX
          RANGE: [304, 312]
          TYPE: decimal
DATA_FILE_TRAILER_RECORD:
  TRAILER: true
  FIELDS:
    - NAME: DF_TRL_RECORD_TYPE
      RANGE: [0, 4]
    - NAME: DF_TRL_DATE
      RANGE: [5, 12]
      TYPE: date
    - NAME: DF_TRL_TIME
      RANGE: [13, 16]
    - NAME: DF_TRL_FILE_ID
      RANGE: [17, 22]
      TYPE: numeric
    - NAME: DF_TRL_FILE_NAME
      RANGE: [23, 42]
    - NAME: DF_TRL_RECIPIENT_KEY
      RANGE: [43, 82]
    - NAME: DF_TRL_RECORD_COUNT
      RANGE: [83, 89]
      TYPE: numeric
